theme: jekyll-theme-cayman
title: |
  Cloud-Scale Data for Spring Developers
description: |
  Java + Azure Cosmos DB + Azure Spring Apps + Azure Functions + Azure Cognitive Search + more!
exclude:
  - .build/
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
sass:
  style: compressed